project:
  type: website
  output-dir: docs
render:
      - index.qmd
      - 001-Data.qmd
      - 002-Test.qmd
website:
  title: "Analyse d'enquÃªtes avec R"
  navbar:
    left:
      - 001-Data.qmd
      - 002-Test.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

